s="have a niCe DAY"

print(s)
print(s.upper())
print(s.lower())
print(s.capitalize())
print(s.title())
print(s.swapcase())
print(s.strip())
print(s.center(50))
print(s.center(50,'$'))
print(s.replace('niCe','good'))
print(s.find('DAY'))
print(s.find('a'))
print(s.count('a'))
print(s.join('123'))
print(s.startswith('h'))
print(''.zfill(5))
print(s.split())
print(dir(s))